### ISSUE TITLE
Redesign bootstrap with use of multiple wells

### ISSUE THREAD

**Issue by smenon18** [RowanACM/ACM-Website#7]
Currently we use one well, to streamline the design we should use multiple

**Comment by johnsbuck** [comment]
Keep separate from #6 since it seems that this issue causes a few bugs.

**Comment by smenon18** [comment]
We probably also need more containers

**Comment by RichCerone** [comment]
Can you guys explain why we should use wells? Aren't wells used for insetting content? This usually results in having a gray background. As long as the containers are set to be fluid they should be able to scale with the content. The real issue here is that some content is set to a static size. So even though the containers are scaling the images are going out of bounds do to the fact that they are simply respecting the size they are set at. I am fixing this issue by creating dynamic divs so that images won't clip out of their containers.

**Comment by smenon18** [comment]
Not gonna use wells anymore
